# Generated by Django 3.1.4 on 2021-01-03 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myConcrete_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('Fecha', models.CharField(blank=True, default='', max_length=100)),
                ('Cantidad', models.FloatField()),
                ('Empresa', models.CharField(blank=True, default='', max_length=200)),
                ('RUC', models.IntegerField()),
                ('Cemento', models.FloatField()),
                ('Agregado_1', models.FloatField()),
                ('Agregado_2', models.FloatField()),
                ('Agua', models.IntegerField()),
                ('Aditivo_1', models.IntegerField()),
                ('T_Producción', models.TimeField()),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
