# Generated by Django 3.1.7 on 2021-03-15 15:36

from django.db import migrations, models
import myConcreteREST.models


class Migration(migrations.Migration):

    dependencies = [
        ('myConcreteREST', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myconcrete_data',
            name='fecha',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='myconcrete_data',
            name='lote',
            field=models.CharField(default=myConcreteREST.models.myConcrete_Data.lote_string, max_length=100),
        ),
    ]
